experiment:
  name: ppo_fullobs_basereward_6rooms
  seed: 42
  total_timesteps: 20000000
  checkpoint_every: 500000
  eval: true
  n_eval_episodes: 10
  eval_freq: 200000

env:
  size: 19
  full_info: false
  n_envs: 8
  render_mode: rgb_array
  # frame_stack: 4
  agent_view_size: 5      # Tamaño del FOV en tiles (7 = default MiniGrid)
  n_rooms: 6

reward:
  key_room_bonus: 0.10
  key_bonus: 0.30
  door_bonus: 0.50
  locked_room_bonus: 0.10
  goal_bonus: 1.00
  step_penalty: 0.001

model:
  policy: CnnPolicy
  features_dim: 512
  pi_layers: [256, 256]
  vf_layers: [256, 256]

  # model:
  #  policy: CnnLstmPolicy   # Para que el config sea descriptivo
  #  features_dim: 512
  #  pi_layers: [128, 128]
  #  vf_layers: [128, 128]
  #  lstm_hidden_size: 256   # Tamaño del estado oculto del LSTM

ppo:
  learning_rate: 0.00025
  n_steps: 1024
  batch_size: 256
  n_epochs: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.05
  vf_coef: 0.5
  max_grad_norm: 0.5

logging:
  tensorboard_subdir: tensorboard
  excel_name: experiments.xlsx