experiment:
  name: ppo_partialobs_roomshaping
  seed: 42
  total_timesteps: 20000000
  checkpoint_every: 500000
  eval: true
  n_eval_episodes: 20
  eval_freq: 200000

env:
  size: 19
  full_obs: false
  n_envs: 8
  render_mode: rgb_array
  # frame_stack: 4
  agent_view_size: 7      # Tamaño del FOV en tiles (7 = default MiniGrid)

reward:
  key_room_bonus: 0.10
  key_bonus: 0.30
  door_bonus: 0.50
  locked_room_bonus: 0.10
  goal_bonus: 1.00
  step_penalty: 0.001

# model: (comentado para probar el RecurrentPPO)
#   policy: CnnPolicy
#   features_dim: 512
#   pi_layers: [256, 256]
#   vf_layers: [256, 256]

model:
  policy: CnnLstmPolicy   # Para que el config sea descriptivo
  features_dim: 512
  pi_layers: [128, 128]
  vf_layers: [128, 128]
  lstm_hidden_size: 128   # Tama�o del estado oculto del LSTM

ppo:
  learning_rate: 0.0001
  n_steps: 512
  batch_size: 128
  n_epochs: 3
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.1
  ent_coef: 0.01
  vf_coef: 1.0
  max_grad_norm: 0.5

logging:
  tensorboard_subdir: tensorboard
  excel_name: experiments.xlsx